### ISSUE TITLE
Thermal Seek Pro times out on frame request

### ISSUE THREAD

**Issue by eutectic** [maartenvds/libseek-thermal#1]
Hello, thanks for making this library.  Tried to get it running on an ubuntu machine with a seek thermal pro and I'm running into a timeout once it tries to frame.   Any ideas?

[Here's a link](https://gist.github.com/eutectic/affd3e94ce62157b9a3a8efe00aedcc3) to a gist of the output from test_pro with DEBUG enabled.

**Comment by maartenvds** [comment]
Hi, thanks for trying. Will take a look at it.

**Comment by maartenvds** [comment]
Sorry for the delay, was quite busy lately. It seems that bulk transfer fails, initialize goes well. I have only one pro camera at my disposal so I never tested it on a second camera. In this way, I can only guess what is going wrong at your side. If possible, can you create maybe a wireshark dump of the usb traffic while running the program? Even better would be that you could capture the usb traffic when running the seek android app. I did this by running the android app on an android emulator (genymobile) on my linux desktop. If I then started wireshark on my desktop (after forwarding the usb device to genymobile; see howto here: http://scrumsofanarchy.com/interfacing-physical-otg-devices-to-genymotion-android-vm/), I could see the usb traffic. This allowed me to mimic the commands send by the seek app.
Sorry that I cannot help you any further in a more easy way.

**Comment by maartenvds** [comment]
By the way, did you try to increase the timeout for bulk transfer? You can do this in SeekDevice.h line 68
