### ISSUE TITLE
How to get the initial usb command of seek pro

### ISSUE THREAD

**Issue by Tonykids** [maartenvds/libseek-thermal#16]
Great project and I have modified the old SeekOFix on Windows with your initial command of seek pro and it works well.
What i want to know is how did you manage to get the right initial command of seek pro ?
just use the USB protocol analyzer or other ways?

**Comment by maartenvds** [comment]
Sniffing USB trafic with wireshark on a host machine while the android app was running on a virtual android machine (on the same host), communicating with the camera. I just mimicked the behavior of the initialization procedure.

**Comment by Tonykids** [comment]
I tried vmware workstation and vitrualbox but when i connect the device into the virtual machine , the 
 device do not show in wireshark  on the host.
my host is windows 7,or I need a Linux platform?

**Comment by maartenvds** [comment]
I used genymotion android emulator on a native linux machine (ubuntu). Wireshark was running on the native linux. In addition I had to forward the usb device to the emulator so it could access it. You could install genymotion on windows and try the same thing. Never did that myself though.

**Comment by Tonykids** [comment]
Succeed !
Thanks a lot !
