### ISSUE TITLE
libusb failure in seek_thermal

### ISSUE THREAD

**Issue by philko4711** [maartenvds/libseek-thermal#21]
Hello,

at first, I wanna thank you for this lib. I use it with a seek_thermal_pro and it works perfectly. Unfortunately, I have an issue when I connect a seek_thermal camera. When I start the see_test example it returns:
Error: libusb init failed: LIBUSB_ERROR_ACCESS
Error: open failed
failed to open seek cam

Cheers,

Phil

**Comment by maartenvds** [comment]
Did you set the permissions correctly for the device?

**Comment by philko4711** [comment]
I just realized. I havent. Thank you very much it is working fine now.
