### ISSUE TITLE
udev rule doc error

### ISSUE THREAD

**Issue by fnoop** [maartenvds/libseek-thermal#4]
Hi, according to the README:
```SUBSYSTEM=="usb", ATTRS{idVendor}=="289D", ATTRS{idProduct}=="XXXX", MODE="0666", GROUP="users"```

However, at least on Raspbian (Debian Jessie), I had to use:
```SUBSYSTEM=="usb", ATTRS{idVendor}=="289d", ATTRS{idProduct}=="XXXX", MODE="0666", GROUP="users"```

(Lower case 'd' in 289d)
This had me stumped for a while!

**Comment by maartenvds** [comment]
Is very likely to be a typo. Will modify it

**Comment by maartenvds** [comment]
Done
