### ISSUE TITLE
Lots of artifacts in the image

### ISSUE THREAD

**Issue by fnoop** [maartenvds/libseek-thermal#6]
I see lots of dots/artifacts in the image.  These are static - the all remain in the same place - no matter where the camera is pointed.  They are not present in the libseek images.  Am I missing a step somewhere to correct bad pixels or something?
<img width="208" alt="screen shot 2017-05-20 at 18 37 39" src="https://cloud.githubusercontent.com/assets/8210968/26278143/a5e9b4b4-3d8b-11e7-9991-be95334e7949.png">

**Comment by maartenvds** [comment]
Can you give a bit more context? What camera are you using and are you using the provided samples or code of your own? Is the rest of the image as expected besides the white dots (since you seem to be pointing at a cold background)? library handles bad pixels so normally no need to correct them.

**Comment by fnoop** [comment]
Sorry, this is an original seek XR (believe it's now called compact XR?), using the standard 'seek_test' code.  As you can see below the picture is excellent, apart from these artifacts.  They seem to be the same on different invocations and even after it has been turned off for a long time.
![screen shot 2017-05-21 at 07 24 36](https://cloud.githubusercontent.com/assets/8210968/26281684/d280678c-3df6-11e7-8256-9ffe61dc35f9.png)

**Comment by maartenvds** [comment]
Looks like the dead pixel filter is doing a bad job :D. I created a new branch called 'dead_pixel_test' where I added some code that writes out 3 .png files. Can you compile this code and run it on your camera using the 'seek_test' executable? It will exit automatically once it has written the 3 .png files in the current directory. If you then send me the 3 files in a zip/tar container, I'm able to reproduce what you are seeing.

**Comment by fnoop** [comment]
Done, attached, thanks :)
[dead_pixel_frames.zip](https://github.com/maartenvds/libseek-thermal/files/1016767/dead_pixel_frames.zip)

**Comment by maartenvds** [comment]
I found the problem, a bit of a naive implementation of me. Currently working on a solution.

**Comment by maartenvds** [comment]
Hi, I fixed the dead pixel filter and tested it on your camera images. It looks as expected. The fix is on the development branch. Can you verify the patch? I still have to test it on my camera before merging it to master but I currently don't have it here.

**Comment by fnoop** [comment]
Confirmed fixed my dead pixels.  Thanks so much :)
