### ISSUE TITLE
Run on Raspberrypi 5

### ISSUE THREAD

**Issue by Glamoth-Firefly-AR26710** [maartenvds/libseek-thermal#82]
Can I use command "seek_viewer --camtype=seekpro --colormap=11 --mode=v4l2 --output=/dev/video0"
and use opencv videocapture to get image on Raspberrypi 5?

**Comment by Bostwickenator** [comment]
Assuming you have v4l2 loopback installed and nothing else is using
`/dev/video0` then yes
